export const Auth = {
  INIT_USER: 'INIT_USER',
  INIT_FOLLOWING: 'INIT_FOLLOWING',
  SET_BALANCE: 'SET_BALANCE',
  LOGOUT_USER: 'LOGOUT_USER',
};

export const User = {
  TOGGLE_FOLLOW: 'TOGGLE_FOLLOW',
  UPDATE_USER: 'UPDATE_USER',
};
