export const MEMENTO_DOMAIN = [
  { value: 'act', label: 'Activism' },
  { value: 'art', label: 'Art' },
  { value: 'biz', label: 'Business' },
  { value: 'crypto', label: 'Crypto' },
  { value: 'design', label: 'Design' },
  { value: 'diy', label: 'DIY' },
  { value: 'edu', label: 'Education' },
  { value: 'event', label: 'Event' },
  { value: 'fashion', label: 'Fashion' },
  { value: 'food', label: 'Food' },
  { value: 'gg', label: 'Game' },
  { value: 'info', label: 'General' },
  { value: 'health', label: 'Health' },
  { value: 'life', label: 'Lifestyle' },
  { value: 'music', label: 'Music' },
  { value: 'movie', label: 'Movie' },
  { value: 'pet', label: 'Pet' },
  { value: 'photo', label: 'Photography' },
  { value: 'science', label: 'Science' },
  { value: 'sport', label: 'Sport' },
  { value: 'tech', label: 'Technology' },
];

export const MEMENTO_TYPE = ['Public', 'Personal'];
